apiVersion: v1
kind: Service
metadata:
  name: {{ include "condukt-site.fullname" . }}
  labels:
    {{- include "condukt-site.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "condukt-site.webSelectorLabels" . | nindent 4 }}
