defmodule Condukt.Workflows.LockfileTest do
  use ExUnit.Case, async: true

  alias Condukt.Workflows.{Lockfile, Resolver}

  @package %{
    version: "1.2.3",
    url: "https://github.com/tuist/condukt-tools",
    sha256: "abcdef",
    integrity: "sha256-q83v",
    dependencies: ["github.com/foo/bar"]
  }

  @tag :tmp_dir
  test "loads missing lockfiles as :missing", %{tmp_dir: tmp_dir} do
    assert Lockfile.load(Path.join(tmp_dir, "condukt.lock")) == :missing
  end

  @tag :tmp_dir
  test "writes deterministic TOML and round-trips it", %{tmp_dir: tmp_dir} do
    path = Path.join(tmp_dir, "condukt.lock")

    lockfile = %Lockfile{
      packages: %{
        "github.com/tuist/condukt-tools" => @package,
        "github.com/alpha/tools" => %{@package | version: "0.1.0", dependencies: []}
      }
    }

    assert :ok = Lockfile.write(lockfile, path)
    assert {:ok, loaded} = Lockfile.load(path)
    assert loaded.packages["github.com/tuist/condukt-tools"].version == "1.2.3"

    content = File.read!(path)
    assert content =~ "# Auto-generated by mix condukt.workflows.lock. Do not edit by hand."

    assert String.match?(
             content,
             ~r/\[packages\."github\.com\/alpha\/tools"\].*\[packages\."github\.com\/tuist\/condukt-tools"\]/s
           )
  end

  test "checks requirement satisfaction" do
    lockfile = %Lockfile{packages: %{"github.com/tuist/condukt-tools" => @package}}

    assert Lockfile.satisfies?(lockfile, [
             %Resolver.Requirement{url: "github.com/tuist/condukt-tools", version_spec: "^1.0.0"}
           ])

    assert Lockfile.satisfies?(lockfile, [
             %Resolver.Requirement{url: "github.com/tuist/condukt-tools", version_spec: "~1.2.0"}
           ])

    assert Lockfile.satisfies?(lockfile, [
             %Resolver.Requirement{url: "github.com/tuist/condukt-tools", version_spec: ">= 1.0.0"}
           ])

    refute Lockfile.satisfies?(lockfile, [
             %Resolver.Requirement{url: "github.com/tuist/condukt-tools", version_spec: "< 1.0.0"}
           ])

    refute Lockfile.satisfies?(lockfile, [%Resolver.Requirement{url: "github.com/missing/tools", version_spec: "*"}])
  end
end
